//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoopFit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoopFit.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string btnActivity_Profile_Text {
            get {
                return ResourceManager.GetString("btnActivity_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string btnActivity_Text {
            get {
                return ResourceManager.GetString("btnActivity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string btnEditProfile_Profile_Text {
            get {
                return ResourceManager.GetString("btnEditProfile_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome_Profile_Text {
            get {
                return ResourceManager.GetString("btnHome_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string btnHome_Text {
            get {
                return ResourceManager.GetString("btnHome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string btnLoadActivityUser_Activity_Text {
            get {
                return ResourceManager.GetString("btnLoadActivityUser_Activity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string btnLogOut_Profile_Text {
            get {
                return ResourceManager.GetString("btnLogOut_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string btnLogOut_Text {
            get {
                return ResourceManager.GetString("btnLogOut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string btnSubmitLanguage_Profile_Text {
            get {
                return ResourceManager.GetString("btnSubmitLanguage_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity.
        /// </summary>
        internal static string lblActivity_Activity_Text {
            get {
                return ResourceManager.GetString("lblActivity_Activity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language :.
        /// </summary>
        internal static string lblChangeLanguage_Profile_Text {
            get {
                return ResourceManager.GetString("lblChangeLanguage_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string lblContactUs_Text {
            get {
                return ResourceManager.GetString("lblContactUs.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content.
        /// </summary>
        internal static string lblContent_Home_Text {
            get {
                return ResourceManager.GetString("lblContent_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See how LoopFit processes your clothes..
        /// </summary>
        internal static string lblDescContent_Home_Text {
            get {
                return ResourceManager.GetString("lblDescContent_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate your clothes easily here.\r\n.
        /// </summary>
        internal static string lblDescDonate_Home_Text {
            get {
                return ResourceManager.GetString("lblDescDonate_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find our recycled clothing products..
        /// </summary>
        internal static string lblDescProduct_Home_Text {
            get {
                return ResourceManager.GetString("lblDescProduct_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        internal static string lblDonate_Home_Text {
            get {
                return ResourceManager.GetString("lblDonate_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name :.
        /// </summary>
        internal static string lblFullName_Profile_Text {
            get {
                return ResourceManager.GetString("lblFullName_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password :.
        /// </summary>
        internal static string lblPasword_Profile_Text {
            get {
                return ResourceManager.GetString("lblPasword_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string lblPhoneNumber_Profile_Text {
            get {
                return ResourceManager.GetString("lblPhoneNumber_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Product.
        /// </summary>
        internal static string lblProduct_Home_Text {
            get {
                return ResourceManager.GetString("lblProduct_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string lblProfile_Profile_Text {
            get {
                return ResourceManager.GetString("lblProfile_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Our Social Media.
        /// </summary>
        internal static string lblSosmed_Home_Text {
            get {
                return ResourceManager.GetString("lblSosmed_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username :.
        /// </summary>
        internal static string lblUsername_Profile_Text {
            get {
                return ResourceManager.GetString("lblUsername_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string lblWelcome_Home_Text {
            get {
                return ResourceManager.GetString("lblWelcome_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string linkLabel2_Home_Text {
            get {
                return ResourceManager.GetString("linkLabel2_Home.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string llProfile_Profile_Text {
            get {
                return ResourceManager.GetString("llProfile_Profile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string llProfile_Text {
            get {
                return ResourceManager.GetString("llProfile.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page showcases a summary of your recent and past donations, giving you a detailed record of the clothing items you’ve contributed. Each donation has played an important role in supporting our mission in fashion sustainability. Thank you for your generosity and contributions that truly make a difference and help us create a more sustainable future!.
        /// </summary>
        internal static string txtDescription_Activity_Text {
            get {
                return ResourceManager.GetString("txtDescription_Activity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let’s take action for a sustainable future! With LoopFit, you can donate your clothes, track the recycling process by our content, and explore unique products made from upcycled fabrics. Together, we can reduce textile waste and embrace a circular economy!.
        /// </summary>
        internal static string txtDescription_Home_Text {
            get {
                return ResourceManager.GetString("txtDescription_Home.Text", resourceCulture);
            }
        }
    }
}
